export const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  it: 'Italian',
  pt: 'Portuguese',
  ru: 'Russian',
  ja: 'Japanese',
  ko: 'Korean',
  zh: 'Chinese',
  chs: 'Chinese (Simplified)',
  cht: 'Chinese (Traditional)',
  ar: 'Arabic',
  hi: 'Hindi',
  nl: 'Dutch',
  sv: 'Swedish',
  no: 'Norwegian',
  da: 'Danish',
  fi: 'Finnish',
  pl: 'Polish',
  cs: 'Czech',
  sk: 'Slovak',
  hu: 'Hungarian',
  ro: 'Romanian',
  bg: 'Bulgarian',
  hr: 'Croatian',
  sr: 'Serbian',
  sl: 'Slovenian',
  lt: 'Lithuanian',
  lv: 'Latvian',
  et: 'Estonian',
  el: 'Greek',
  tr: 'Turkish',
  he: 'Hebrew',
  fa: 'Persian',
  ur: 'Urdu',
  bn: 'Bengali',
  pa: 'Punjabi',
  gu: 'Gujarati',
  mr: 'Marathi',
  ta: 'Tamil',
  te: 'Telugu',
  kn: 'Kannada',
  ml: 'Malayalam',
  th: 'Thai',
  vi: 'Vietnamese',
  id: 'Indonesian',
  ms: 'Malay',
  tl: 'Tagalog',
  sw: 'Swahili',
  uk: 'Ukrainian',
  ca: 'Catalan',
  eu: 'Basque',
  gl: 'Galician',
  af: 'Afrikaans',
  sq: 'Albanian',
  hy: 'Armenian',
  az: 'Azerbaijani',
  be: 'Belarusian',
  bs: 'Bosnian',
  ka: 'Georgian',
  is: 'Icelandic',
  kk: 'Kazakh',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  mk: 'Macedonian',
  mn: 'Mongolian',
  ne: 'Nepali',
  nn: 'Norwegian Nynorsk',
  si: 'Sinhala',
  tg: 'Tajik',
  tt: 'Tatar',
  uz: 'Uzbek',
  cy: 'Welsh',
  eo: 'Esperanto',
  ga: 'Irish',
  gd: 'Scottish Gaelic',
  ku: 'Kurdish',
  mt: 'Maltese',
  so: 'Somali',
  yi: 'Yiddish',
  zu: 'Zulu',
  xh: 'Xhosa',
};

/**
 * Get the full language name for a language code
 */
export function getLanguageName(code: string): string {
  return LANGUAGE_NAMES[code.toLowerCase()] || code.toUpperCase();
}
